Module6 task1
htmlacademy-adaptive/1435831-pognali-20 pull request #9
Opened 2020-08-25 21:40 UTC by ubitinonevami

2020-08-29 14:17 UTC, redly commented on source/sass/blocks/add-plan.scss
> +  }
Тут неверный подход, не нужно делать кнопки разных размеров и подгонять их под размер иконки

Лучше сделать чтобы область клика была одинаковой, то есть саму кнопку сделать побольше
Если измерить иконку, ее ширина 14px, отступ слева от поля тоже 14px
Чтобы сделать сбалансированную ширину, давай и справа зададим отступ 14px

Итого наша ширина кнопки будет – (14 отступ слева + 14 ширина иконка + 14 отступ справа) = 42
Высота поля тоже 42, поэтому можно задать у всей кнопки width и height по 42

Из-за того, что высота и ширина стали одинаковыми не надо жестко подгонять положение иконки через top и тп

Если обернуть поле + иконки в общий div, у которого будет position: relative тогда все станет еще проще, top всегда будет 0 и отличия у кнопок будут только в фоновой иконке и положению по горизонтали

Итого, нужно обновить разметку
```html
<div class="plan-filters__input-number-wrapper">
    <button type="button" class="plan-filters__toggle plan-filters__toggle--minus" data-direction="minus">-</button>
    <input class="plan-filters__input" name="companion" id="companions" type="number" value="2">
    <button type="button" class="plan-filters__toggle plan-filters__toggle--plus" data-direction="plus">+</button>
</div>
```

Обрати внимание, что лучше использовать корректные input type, я заменил на number, так как вводить можно числа

Новая разметка позволяет нам заметно сократить стили

```scss
.plan-filters__toggle {
  background-repeat: no-repeat;
  background-position: 50% 50%;
  border: none;
  position: absolute;
  top: 0;
  opacity: 0.3;
  height: 42px;
  width: 42px;

  &--minus {
    background-image: url("../img/qty-minus-mobile.svg");
    left: 0;
  }

  &--plus {
    background-image: url("../img/qty-plus-mobile.svg");
    right: 0;
  }
}
```

У кнопок (<button> в разметке) есть дефолтные стили браузера, которые обычно нужно сбрасывать – это padding, border, background

Я обычно, как и по аналогии с no-list, делаю mixin no-btn и использую для всех кнопок

```scss
@mixin no-btn {
  background: none;
  border: none;
  padding: 0;
}
```

2020-08-29 14:20 UTC, redly commented on source/sass/blocks/add-plan.scss
> +    background: url("../img/small-cross.svg") no-repeat;
А зачем? Ты же выше указываешь такой же стиль, а тут этой полной записью сбросишь и background-color, и background-size и background-position

Если ты их переопределяешь специально, то стоит переопределить свойства, которые нужно сбросить точечно (только их)

2020-08-29 14:21 UTC, redly commented on source/sass/blocks/add-plan.scss
> +    border-radius: 0%;
Когда указываешь 0, не нужно указывать размерность, нужно просто `border-radius: 0`

Размерность у 0 нужно указывать только у transition-delay, animation-delay

`transition-delay: 0` - будет ошибка, браузер проигнорирует
`transition-delay: 0s` - все будет корректно

2020-08-29 14:25 UTC, redly commented on source/sass/blocks/add-plan.scss
> +}
Так как модификатор не используется отдельно, а всегда с классом который модифицирует, не надо писать все те же самые стили что и выше

```scss
.plan-filters__comment--last {
  &::placeholder {
    color: $special_grey;
  }
}
```

2020-08-29 14:26 UTC, redly commented on source/sass/blocks/add-plan.scss
> +    padding: 10px 14px;
padding стоит задать полю, а не placeholder'у

тоже самое касается и font-size
а line-height лучше вообще не указывать для полей, кроме textarea

2020-08-29 14:28 UTC, redly commented on source/sass/blocks/address.scss
> +    color: rgba(#ffffff, 0.3);
В SCSS можно так `color: rgba($basic-white, 0.3);`

2020-08-29 14:28 UTC, redly commented on source/sass/blocks/btn.scss
> +    color: rgba($basic-blue-light, $alpha: 0.3);
Лучше просто `color: rgba($basic-blue-light, 0.3);
 `

2020-08-29 14:33 UTC, redly commented on source/sass/blocks/btn.scss
> +.btn-back {
Лучше в отдельный файл. Могут придраться на защите, потому что технически это БЭМ блок

2020-08-29 14:35 UTC, redly commented on source/sass/blocks/btn.scss
> +  text-align: center;
Ты задаешь свойства text-decoration, text-transform в начале файла, а text-align в конце
Когда все так в разнобой, начинают со временем дублироваться свойства, особенно когда стилей у селектора много. За тобой такой ошибки не замечал, но тем не менее лучше свойства у селектора как-нибудь сортировать

Можно по алфавиту, можно по предназначению, можно комбинированно
Подход академии по сортировке тут описан – https://codeguide.academy/html-css.html

2020-08-29 14:40 UTC, redly commented on source/sass/blocks/map.scss
> +  background: url("img/map-mobile@1x.jpg, img/map-mobile@2x.jpg 2x");
Тут что-то странное происходит, так это не работает в CSS

Ты же выше корректно все делаешь, когда используешь 
`@media (min-resolution: $retina-dpi), (min-resolution: $retina-dppx) {` 

Ну а вообще карта должна быть сделана не фоном, а через picture + img

2020-08-29 14:41 UTC, redly commented on source/sass/blocks/page-header.scss
> +.page-header-wrapper {
Опять же в отдельный файл

2020-08-29 14:41 UTC, redly commented on source/sass/blocks/plans.scss
> +  background-color: rgb(223, 227, 240);
rgb заменить на hex, чтобы было однообразно

2020-08-29 14:45 UTC, redly commented on source/sass/blocks/promotion.scss
> +    }
Зачем такие сложности через content и тп
Нужно внутри кнопки сделать span с текстом "Регистрация", который показывается только на десктопе

Абсолютное позиционирование для кнопки тоже не нужно

2020-08-29 14:46 UTC, redly commented on source/sass/blocks/transport.scss
> +    background-position: center;
Нужно как и ниже, просто `background-image: url("../img/plane.svg")`

2020-08-30 15:57 UTC, redly requested changes

2020-08-30 15:57 UTC, redly commented on source/catalog.html
> +      </path>
В svg path можно не закрывать через `</path>` достаточно ставить закрывающий слеш в конце тега, т.е писать так `<path d="M18 …" />`

Например, так ты делаешь для иконки vk ниже (`symbol id="vk-icon"`)

2020-08-30 15:57 UTC, redly commented on source/catalog.html
> +  </svg>
Нужно закрыть сначала symbol и уже потом svg

2020-08-30 15:57 UTC, redly commented on source/catalog.html
> +      <ellipse cx="14.3" cy="2" rx="2.1" ry="2"></ellipse>
Тоже одиночный тег, нужно так – `<ellipse cx="14.3" cy="2" rx="2.1" ry="2" />`

Подробнее про все paths – https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths

2020-08-30 15:57 UTC, redly commented on source/index.html
> +  </svg>
Слишком рано закрыла svg
Из-за этого иконки ниже выпадают из svg спрайта, поэтому например иконка instagram в футере не отображается

Обрати внимание на комментарии к svg-спрайту выше

Как поправишь их и исправишь тут закрывающий тег, можно общий спрайт будет вставить на все страницы. Не обязательно собирать спрайт под каждую страницу с иконками, которые используются только там. Проще один общий

На этапе автоматизации в верстку спрайт будет собираться автоматически, поэтому сильно время на это лучше не тратить

2020-09-02 21:28 UTC, ubitinonevami commented
Привет!
Фоны поправила, к макету все основные блоки подогнали, мелкие декоративные элементы не особо трогала.
1. Не могу добиться отображения иконки инстаграмма
2. В блоке направления проблема с аватаркой и левелом в десктопной версии, не могу добиться их отображения. Высокий з-индекс не работает
3. В этом же блоке у инпутов пропадает часть рамки, если задавать им марджин или паддинг
4. В попутчиках не сообржу как поступить: есть блок фильтрация по странам и затем "Европа Азия и тд", в мобильной версии этот список отображается при раскрытии фильтра,  а на планшете и десктопе уже в самом этом меню.

2020-09-06 15:25 UTC, merged